// Redux module for ActionTypes state/actions.
export const CHAT_BOT_REQUEST = 'CHAT_BOT_REQUEST';
export const CHAT_BOT_SUCCESS = 'CHAT_BOT_SUCCESS';
export const CHAT_BOT_FAILURE = 'CHAT_BOT_FAILURE';
export const CHAT_BOT_CLEAR = 'CHAT_BOT_CLEAR';
export const CHAT_BOT_STREAM_START = 'CHAT_BOT_STREAM_START';
export const CHAT_BOT_STREAM_CHUNK = 'CHAT_BOT_STREAM_CHUNK';
export const CHAT_BOT_STREAM_COMPLETE = 'CHAT_BOT_STREAM_COMPLETE';
export const CHAT_BOT_HISTORY_REQUEST = 'CHAT_BOT_HISTORY_REQUEST';
export const CHAT_BOT_HISTORY_SUCCESS = 'CHAT_BOT_HISTORY_SUCCESS';
export const CHAT_BOT_HISTORY_FAILURE = 'CHAT_BOT_HISTORY_FAILURE';
export const CHAT_BOT_RETRY = 'CHAT_BOT_RETRY';

